---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-ingress
  namespace: homeassistant
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ha.digitalinfo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ha-lb-svc
            port:
              name: http
