---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ha-allow-pods
  namespace: homeassistant
spec:
  podSelector:
    matchLabels:
      app: home-assistant
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
          - key: name
            operator: In
            values:
              - frigate
        matchLabels:
          name: frigate
    - namespaceSelector:
        matchExpressions:
          - key: name
            operator: In
            values:
              - node-red
        matchLabels:
          name: node-red
    - namespaceSelector:
        matchExpressions:
          - key: name
            operator: In
            values:
              - mosquitto
        matchLabels:
          name: mosquitto
    - namespaceSelector:
        matchExpressions:
          - key: name
            operator: In
            values:
              - node-red
        matchLabels:
          name: node-red
    - namespaceSelector:
        matchExpressions:
          - key: name
            operator: In
            values:
              - zigbee2mqtt
        matchLabels:
          name: zigbee2mqtt
  policyTypes:
  - Ingress
