---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ha-deny-all
  namespace: homeassistant
spec:
  podSelector: {}
  matchLabels:
    app: home-assistant
  ingress:
  - {}
  policyTypes:
  - Ingress