---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ha-allow-pods
  namespace: homeassistant
spec:
  podSelector:
    matchLabels:
      app: home-assistant
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: esphome
    - podSelector:
        matchLabels:
          app: frigate
    - podSelector:
        matchLabels:
          app: mosquitto
    - podSelector:
        matchLabels:
          app: node-red
    - podSelector:
        matchLabels:
          app: zigbee2mqtt
