---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: homeassistant
spec:
  podSelector:
    matchLabels:
      app: home-assistant
  policyTypes:
  - Ingress