---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-config-root
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-retain
  
